FROM alpine:3

LABEL author="Ikhwan Pramuditha"
LABEL company="Mobile and Cloud Computing Architecture Lab" website="https://uny.ac.id"

RUN mkdir hello
RUN echo "Males hello world lagi" > hello/world.txt

CMD cat "hello/world.txt"
